"""Build provenance payloads for answers generated by the multi-hop pipeline."""

from __future__ import annotations

import os
import sys
from typing import Dict, List, Sequence

if __package__ in {None, ""}:
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    from multi_hop_causal_rag.multi_hop.chain_builder import EvidenceChain
else:
    from ..multi_hop.chain_builder import EvidenceChain


def build_provenance_payload(answer: str, chain: EvidenceChain, retrieval_queries: Sequence[str] | None = None) -> Dict[str, object]:
    """Assemble the answer, causal path, and document sources into a provenance object."""

    sources: List[str] = []
    source_metadata: List[Dict[str, object]] = []
    for result in chain.evidence:
        if result.document.doc_id not in sources:
            sources.append(result.document.doc_id)
            source_metadata.append(
                {
                    "doc_id": result.document.doc_id,
                    "source": result.document.source,
                    "metadata": result.document.metadata,
                    "score": result.score,
                }
            )

    return {
        "answer": answer,
        "retrieval_queries": list(retrieval_queries or []),
        "evidence_chain": [f"{triple.cause} -> {triple.effect}" for triple in chain.triples],
        "document_sources": sources,
        "source_details": source_metadata,
        "causal_path": chain.nodes,
        "validations": chain.validations,
    }
